{{- $templateConfig := (merge (dict "name" "openvpn-gwclient" "module" "networking") .) -}}
{{- $gatewayConfig := (merge (dict "name" "gateway" "module" "networking" "version" .Values.networking.gatewayTemplates.container.gateway.image.version) .) -}}
{{- $openvpnConfig := (merge (dict "name" "gateway-openvpn" "module" "networking" "version" .Values.networking.gatewayTemplates.container.openvpn.image.version) .) -}}
{{- $geneveConfig := (merge (dict "name" "gateway-geneve" "module" "networking" "version" .Values.networking.gatewayTemplates.container.geneve.image.version) .) -}}

{{- if .Values.networking.enabled }}

apiVersion: networking.liqo.io/v1beta1
kind: OvpnGatewayClientTemplate
metadata:
  name: {{ $templateConfig.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "liqo.labels" $templateConfig | nindent 4 }}
spec:
  objectKind:
    apiVersion: networking.liqo.io/v1beta1
    kind: OvpnGatewayClient
  template:
    metadata:
      {{- include "liqo.metadataTemplate" $templateConfig | nindent 6 }}
    spec:
      secretRef:
        name: "{{"{{ .Spec.SecretRef.Name }}"}}"
      deployment:
        metadata:
          {{- include "liqo.metadataTemplate" $templateConfig | nindent 10 }}
        spec:
          replicas: {{ .Values.networking.gatewayTemplates.replicas }}
          strategy:
            type: Recreate
          selector:
            matchLabels:
              {{- include "liqo.selectorTemplate" $templateConfig | nindent 14 }}
          template:
            metadata:
              {{- include "liqo.metadataTemplate" $templateConfig | nindent 14 }}
            spec:
              serviceAccount: "{{"{{ .Name }}"}}"
              serviceAccountName: "{{"{{ .Name }}"}}"
              {{- include "liqo.imagePullSecrets" . | nindent 14 }}
              containers:
              - name: gateway
                image: {{ .Values.networking.gatewayTemplates.container.gateway.image.name }}{{ include "liqo.suffix" $gatewayConfig }}:{{ include "liqo.version" $gatewayConfig }}
                imagePullPolicy: {{ .Values.pullPolicy }}
                args:
                - --name={{"{{ .Name }}"}}
                - --namespace={{"{{ .Namespace }}"}}
                - --remote-cluster-id={{"{{ .ClusterID }}"}}
                - --gateway-uid={{"{{ .GatewayUID }}"}}
                - --node-name={{"$(NODE_NAME)"}}
                - --pod-name={{"$(POD_NAME)"}}
                - --mode=client
                - --container-name=gateway
                - --concurrent-containers-names=openvpn,geneve
                {{- if .Values.common.globalAnnotations }}
                {{- $d := dict "commandName" "--global-annotations" "dictionary" .Values.common.globalAnnotations -}}
                {{- include "liqo.concatenateMap" $d | nindent 16 }}
                {{- end }}
                {{- if .Values.common.globalLabels }}
                {{- $d := dict "commandName" "--global-labels" "dictionary" .Values.common.globalLabels -}}
                {{- include "liqo.concatenateMap" $d | nindent 16 }}
                {{- end }}
                {{- if .Values.metrics.enabled }}
                - --metrics-address=:8082
                {{- end }}
                - --health-probe-bind-address=:8083
                - --ping-enabled=true
                - --ping-loss-threshold={{ .Values.networking.gatewayTemplates.ping.lossThreshold }}
                - --ping-interval={{ .Values.networking.gatewayTemplates.ping.interval }}
                - --ping-update-status-interval={{ .Values.networking.gatewayTemplates.ping.updateStatusInterval }}
                - --leader-election=true
                {{- if not .Values.requirements.kernel.enabled }}
                - --disable-kernel-version-check
                {{- end }}
                volumeMounts: 
                - name: ipc 
                  mountPath: /ipc
                ports:
                {{- if .Values.metrics.enabled }}
                - containerPort: 8082
                  name: gw-metrics
                {{- end }}
                - containerPort: 8083
                  name: healthz
                env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                securityContext:
                  privileged: true
                  capabilities:
                    add:
                    - NET_ADMIN
                    - NET_RAW
              - name: openvpn
                image: {{ .Values.networking.gatewayTemplates.container.openvpn.image.name }}{{ include "liqo.suffix" $openvpnConfig }}:{{ include "liqo.version" $openvpnConfig }}
                imagePullPolicy: {{ .Values.pullPolicy }}
                args:
                - --name={{"{{ .Name }}"}}
                - --namespace={{"{{ .Namespace }}"}}
                - --remote-cluster-id={{"{{ .ClusterID }}"}}
                - --node-name={{"$(NODE_NAME)"}}
                - --pod-name={{"$(POD_NAME)"}}
                - --container-name=openvpn
                - --gateway-uid={{"{{ .GatewayUID }}"}}
                - --mode=client
                - --ifconfig-local-ip=169.254.18.2
                - --ifconfig-remote-ip=169.254.18.1
                - --remote={{"{{ index .Spec.Endpoint.Addresses 0 }}"}}
                - --port={{"{{ .Spec.Endpoint.Port }}"}}
                securityContext:
                  capabilities:
                    add:
                    - NET_ADMIN
                  privileged: true
                volumeMounts:
                - name: openvpn-config
                  mountPath: /etc/openvpn/keys
                - name: ipc 
                  mountPath: /ipc
              - name: geneve
                image: {{ .Values.networking.gatewayTemplates.container.geneve.image.name }}{{ include "liqo.suffix" $geneveConfig }}:{{ include "liqo.version" $geneveConfig }}
                imagePullPolicy: {{ .Values.pullPolicy }}
                args:
                - --name={{"{{ .Name }}"}}
                - --namespace={{"{{ .Namespace }}"}}
                - --remote-cluster-id={{"{{ .ClusterID }}"}}
                - --gateway-uid={{"{{ .GatewayUID }}"}}
                - --node-name={{"$(NODE_NAME)"}}
                - --pod-name={{"$(POD_NAME)"}}
                - --mode=server
                - --container-name=geneve
                - --geneve-port={{ .Values.networking.genevePort }}
                {{- if .Values.metrics.enabled }}
                - --metrics-address=:8086
                {{- end }}
                - --health-probe-bind-address=:8087
                volumeMounts: 
                - name: ipc 
                  mountPath: /ipc
                ports:
                {{- if .Values.metrics.enabled }}
                - containerPort: 8086
                  name: gv-metrics
                {{- end }} 
                - containerPort: 8087
                  name: healthz
                env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                securityContext:
                  capabilities:
                    add:
                    - NET_ADMIN
                    - NET_RAW
              volumes:
              - name: openvpn-config
                secret:
                  secretName: "{{"{{ .Spec.SecretRef.Name }}"}}"
              - name: ipc 
                emptyDir: {}   
{{- end }}
