{{- $templateConfig := (merge (dict "name" "geneve-client" "module" "networking" "isGwTemplate" true) .) -}}
{{- $gatewayConfig := (merge (dict "name" "gateway" "module" "networking" "version" .Values.networking.gatewayTemplates.container.gateway.image.version) .) -}}
{{- $geneveTunnelConfig := (merge (dict "name" "gateway-geneve-tunnel" "module" "networking" "version" .Values.networking.gatewayTemplates.container.geneveTunnel.image.version) .) -}}
{{- $geneveConfig := (merge (dict "name" "gateway-geneve" "module" "networking" "version" .Values.networking.gatewayTemplates.container.geneve.image.version) .) -}}

{{- if .Values.networking.enabled }}

apiVersion: networking.liqo.io/v1beta1
kind: GeneveGatewayClientTemplate
metadata:
  name: {{ $templateConfig.name }}
  labels:
    {{- include "liqo.labels" $templateConfig | nindent 4 }}
spec:
  objectKind:
    apiVersion: networking.liqo.io/v1beta1
    kind: GeneveGatewayClient
  template:
    metadata:
      {{- include "liqo.metadataTemplate" $templateConfig | nindent 6 }}
    spec:
      service:
        metadata:
          name: {{ quote "{{ .Name }}" }}
          namespace: {{ quote "{{ .Namespace }}" }}
          labels:
            {{- include "liqo.labelsTemplate" $templateConfig | nindent 12 }}
          annotations:
            liqo.io/skip-reflection: "true"
          {{- if .Values.networking.gatewayTemplates.server.service.annotations }}
            {{- toYaml .Values.networking.gatewayTemplates.server.service.annotations | nindent 12 }}
          {{- end }}
        spec:
          selector:
            {{- include "liqo.selectorTemplate" (merge (dict "isService" true) $templateConfig) | nindent 12 }}
          type: {{ .Values.networking.gatewayTemplates.geneve.client.service.type }}
          ports:
          - port: {{ .Values.networking.gatewayTemplates.geneve.client.service.port }}
            protocol: UDP
            targetPort: {{ .Values.networking.gatewayTemplates.geneve.client.service.port }}
      deployment:
        metadata:
          {{- include "liqo.metadataTemplate" $templateConfig | nindent 10 }}
        spec:
          replicas: {{ .Values.networking.gatewayTemplates.replicas }}
          strategy:
            type: Recreate
          selector:
            matchLabels:
              {{- include "liqo.selectorTemplate" $templateConfig | nindent 14 }}
          template:
            metadata:
              {{- include "liqo.metadataTemplate" $templateConfig | nindent 14 }}
            spec:
              serviceAccount: "{{"{{ .Name }}"}}"
              serviceAccountName: "{{"{{ .Name }}"}}"
              {{- include "liqo.imagePullSecrets" . | nindent 14 }}
              {{- if .Values.networking.gatewayTemplates.pod.tolerations }}
              tolerations:
              {{- toYaml .Values.networking.gatewayTemplates.pod.tolerations | nindent 14 }}
              {{- end }}
              containers:
              - name: gateway
                image: {{ .Values.networking.gatewayTemplates.container.gateway.image.name }}{{ include "liqo.suffix" $gatewayConfig }}:{{ include "liqo.version" $gatewayConfig }}
                imagePullPolicy: {{ .Values.pullPolicy }}
                args:
                - --name={{"{{ .Name }}"}}
                - --namespace={{"{{ .Namespace }}"}}
                - --remote-cluster-id={{"{{ .ClusterID }}"}}
                - --node-name={{"$(NODE_NAME)"}}
                - --pod-name={{"$(POD_NAME)"}}
                - --gateway-uid={{"{{ .GatewayUID }}"}}
                - --mode=client
                - --container-name=gateway
                - --concurrent-containers-names=geneve-tunnel,geneve
                {{- if .Values.common.globalAnnotations }}
                {{- $d := dict "commandName" "--global-annotations" "dictionary" .Values.common.globalAnnotations -}}
                {{- include "liqo.concatenateMap" $d | nindent 16 }}
                {{- end }}
                {{- if .Values.common.globalLabels }}
                {{- $d := dict "commandName" "--global-labels" "dictionary" .Values.common.globalLabels -}}
                {{- include "liqo.concatenateMap" $d | nindent 16 }}
                {{- end }}
                {{- if .Values.metrics.enabled }}
                - --metrics-address=:8082
                {{- end }}
                - --health-probe-bind-address=:8083
                - --ping-enabled=true
                - --ping-loss-threshold={{ .Values.networking.gatewayTemplates.ping.lossThreshold }}
                - --ping-interval={{ .Values.networking.gatewayTemplates.ping.interval }}
                - --ping-update-status-interval={{ .Values.networking.gatewayTemplates.ping.updateStatusInterval }}
                {{- if gt (int .Values.networking.gatewayTemplates.replicas) 1 }}
                - --leader-election=true
                {{- else }}
                - --leader-election=false
                {{- end }}
                {{- if not .Values.requirements.kernel.enabled }}
                - --disable-kernel-version-check
                {{- end }}
                - --enable-nft-monitor={{ .Values.networking.gatewayTemplates.nftablesMonitor }}
                - --enable-route-monitor={{ .Values.networking.gatewayTemplates.routeMonitor }}
                volumeMounts:
                - name: ipc
                  mountPath: /ipc
                ports:
                {{- if .Values.metrics.enabled }}
                - containerPort: 8082
                  name: gw-metrics
                {{- end }}
                - containerPort: 8083
                  name: healthz
                env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                securityContext:
                  privileged: true
                  capabilities:
                    add:
                    - NET_ADMIN
                    - NET_RAW
              - name: geneve-tunnel
                image: {{ .Values.networking.gatewayTemplates.container.geneveTunnel.image.name }}{{ include "liqo.suffix" $geneveTunnelConfig }}:{{ include "liqo.version" $geneveTunnelConfig }}
                imagePullPolicy: {{ .Values.pullPolicy }}
                args:
                - --name={{"{{ .Name }}"}}
                - --namespace={{"{{ .Namespace }}"}}
                - --remote-cluster-id={{"{{ .ClusterID }}"}}
                - --gateway-uid={{"{{ .GatewayUID }}"}}
                - --mode=client
                - --container-name=geneve-tunnel
                - --l3=true
                - --mtu={{"{{ .Spec.MTU }}"}}
                - --vni={{ .Values.networking.gatewayTemplates.geneve.vni }}
                - --port={{ .Values.networking.gatewayTemplates.geneve.client.service.port }}
                - --remote-address={{"{{ index .Spec.Endpoint.Addresses 0 }}"}}
                - --remote-port={{"{{ .Spec.Endpoint.Port }}"}}
                {{- if .Values.metrics.enabled }}
                - --metrics-address=:8084
                {{- end }}
                - --health-probe-bind-address=:8085
                {{- if gt (int .Values.networking.gatewayTemplates.replicas) 1 }}
                - --leader-election=true
                {{- else }}
                - --leader-election=false
                {{- end }}
                ports:
                {{- if .Values.metrics.enabled }}
                - containerPort: 8084
                  name: gnv-metrics
                {{- end }}
                - containerPort: 8085
                  name: healthz
                securityContext:
                  capabilities:
                    add:
                    - NET_ADMIN
                    - NET_RAW
                volumeMounts:
                - name: ipc
                  mountPath: /ipc
              - name: geneve
                image: {{ .Values.networking.gatewayTemplates.container.geneve.image.name }}{{ include "liqo.suffix" $geneveConfig }}:{{ include "liqo.version" $geneveConfig }}
                imagePullPolicy: {{ .Values.pullPolicy }}
                args:
                - --name={{"{{ .Name }}"}}
                - --namespace={{"{{ .Namespace }}"}}
                - --remote-cluster-id={{"{{ .ClusterID }}"}}
                - --node-name={{"$(NODE_NAME)"}}
                - --pod-name={{"$(POD_NAME)"}}
                - --gateway-uid={{"{{ .GatewayUID }}"}}
                - --mode=server
                - --container-name=geneve
                - --geneve-port={{ .Values.networking.genevePort }}
                {{- if .Values.metrics.enabled }}
                - --metrics-address=:8086
                {{- end }}
                - --health-probe-bind-address=:8087
                {{- if gt (int .Values.networking.gatewayTemplates.replicas) 1 }}
                - --leader-election=true
                {{- else }}
                - --leader-election=false
                {{- end }}
                volumeMounts:
                - name: ipc
                  mountPath: /ipc
                ports:
                {{- if .Values.metrics.enabled }}
                - containerPort: 8086
                  name: gv-metrics
                {{- end }}
                - containerPort: 8087
                  name: healthz
                env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                securityContext:
                  capabilities:
                    add:
                    - NET_ADMIN
                    - NET_RAW
              {{- if .Values.networking.gatewayTemplates.pod.priorityClassName }}
              priorityClassName: {{ .Values.networking.gatewayTemplates.pod.priorityClassName }}
              {{- end }}
              volumes:
              - name: ipc
                emptyDir: {}
{{- end }}
